experiments:
  - name: Cora1
    config_path: './configs/experiments/exp1_cora.yaml'
  - name: Citeseer1
    config_path: './configs/experiments/exp1_citeseer.yaml'
  - name: Pubmed1
    config_path: './configs/experiments/exp1_pubmed.yaml'
  - name: Facebook1
    config_path: './configs/experiments/exp1_facebook.yaml'
  # Add more experiments as needed
data:
  raw_path: ./data/raw
  adj_matrices_path: ./data/adj_matrices
  dataset_src:
    Cora: PyTorch-Geometric/Planetoid/Cora
    Pubmed: PyTorch-Geometric/Planetoid/PubMed
    Citiseer: PyTorch-Geometric/Planetoid/CiteSeer
    Facebook: Pytorch-Geometric/AttributedGraphDataset/Facebook
    ca-HePh:
    p2p-Gnutella04: https://snap.stanford.edu/data/p2p-Gnutella04.html
    BlogCatalog:
    Wiki-Vote: https://snap.stanford.edu/data/wiki-Vote.html
    ca-GrCq: https://snap.stanford.edu/data/ca-GrQc.html
    Wikipedia:
    PPI:

