experiments:
  - name: Cora1
    config_path: './configs/experiments/exp1_cora.yaml'
  - name: Citeseer1
    config_path: './configs/experiments/exp1_citeseer.yaml'
  - name: Pubmed1
    config_path: './configs/experiments/exp1_pubmed.yaml'
  - name: Facebook1
    config_path: './configs/experiments/exp1_facebook.yaml'
  # Add more experiments as needed
data:
  raw_path: ./data/raw
  adj_matrices_path: ./data/adj_matrices
  dataset_src:
    Cora: PyTorch-Geometric/Planetoid/Cora
    Pubmed: PyTorch-Geometric/Planetoid/PubMed # This is not the same as in Chanpuriya et al. Slight differences in the number of nodes
    Citiseer: PyTorch-Geometric/Planetoid/CiteSeer
    Facebook: Pytorch-Geometric/AttributedGraphDataset/Facebook
    ca-HepPh: SNAPDataset/ca-HepPh # This seems to not have the same amount of nodes as in Chanpuriya et al. although they cited the same source
    p2p-Gnutella04: SNAPDataset/p2p-Gnutella04
    BlogCatalog: http://leitang.net/code/social-dimension/data/blogcatalog.mat
    Wiki-Vote: SNAPDataset/wiki-Vote
    ca-GrCq: SNAPDataset/ca-GrQc
    # Wikipedia:
    # PPI:

