experiments:
  - name: Cora1
    config_path: './configs/experiments/exp1_cora.yaml'
  - name: Cora2
    config_path: './configs/experiments/exp2_cora.yaml'
  - name: Cora3
    config_path: './configs/experiments/exp2_cora.yaml'
  - name: Citeseer1
    config_path: './configs/experiments/exp1_citeseer.yaml'
  - name: Pubmed1
    config_path: './configs/experiments/exp1_pubmed.yaml'
  - name: Facebook1
    config_path: './configs/experiments/exp1_facebook.yaml'
  - name: ca-HepPh1
    config_path: './configs/experiments/exp1_ca-hepph.yaml'
  - name: p2p-Gnutella041
    config_path: './configs/experiments/exp1_p2p-gnutella04.yaml'
  - name: Wiki-Vote1
    config_path: './configs/experiments/exp1_wiki-vote.yaml'
  - name: ca-GrQc1
    config_path: './configs/experiments/exp1_ca-grqc.yaml'
  - name: email-Enron1
    config_path: './configs/experiments/exp1_email-enron.yaml'
  # Add more experiments as needed
data:
  raw_path: ./data/raw
  adj_matrices_path: ./data/adj_matrices
  dataset_src:
    Cora: PyTorch-Geometric/Planetoid/Cora
    Pubmed: PyTorch-Geometric/Planetoid/PubMed # This is not the same as in Chanpuriya et al. Slight differences in the number of nodes
    Citeseer: PyTorch-Geometric/Planetoid/CiteSeer
    Facebook: Pytorch-Geometric/AttributedGraphDataset/Facebook
    ca-HepPh: SNAPDataset/ca-HepPh # This seems to not have the same amount of nodes as in Chanpuriya et al. although they cited the same source
    p2p-Gnutella04: SNAPDataset/p2p-Gnutella04
    BlogCatalog: http://leitang.net/code/social-dimension/data/blogcatalog.mat
    Wiki-Vote: SNAPDataset/wiki-Vote
    ca-GrQc: SNAPDataset/ca-GrQc
    email-Enron: SNAPDataset/email-Enron
    # Wikipedia:
    # PPI:
    toy-data-6: generate-toy-data/6 # This is a toy dataset, /20 means 20 triangles
results:
  path: ./results
  logs_path: ./results/logs
  models_path: ./results/models
  plots_path: ./results/plots
  stats_path: ./results/stats
